### ISSUE TITLE
import nlplotでエラーが発生する。

### ISSUE THREAD

**Issue by takapy0210** [takapy0210/nlplot#15]
cf. https://github.com/takapy0210/takapy_blog/issues/1#issue-683849954

---

pip install nlplot自体はエラーなく完了しましたが、import nlplotを実行すると以下のエラーが発生してしまいます。

環境はwin10, Python 3.6.5 |Anacondaです。

>>> import nlplot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\＊＊＊＊＊＊myenv\lib\site-packages\nlplot\__init__.py", line 1, in <module>
    from nlplot.nlplot import *
  File "C:\Users\＊＊＊＊＊＊\myenv\lib\site-packages\nlplot\nlplot.py", line 15, in <module>
    import seaborn as sns
  File "C:\Users\＊＊＊＊＊＊\myenv\lib\site-packages\seaborn\__init__.py", line 2, in <module>
    import matplotlib as mpl
  File "C:\Users＊＊＊＊＊＊\myenv\lib\site-packages\matplotlib\__init__.py", line 174, in <module>
    _check_versions()
  File "C:\Users\＊＊＊＊＊＊\myenv\lib\site-packages\matplotlib\__init__.py", line 159, in _check_versions
    from . import ft2font
ImportError: DLL load failed: 指定されたモジュールが見つかりません。

エラー原因わかりますでしょうか？

**Comment by takapy0210** [comment]
@sinjorjob 
ご連絡が大変遅くなり申し訳ないです. 

nlplotの最新version（v1.4.0）をリリースしたので、そちらで今一度試して見ていただけますでしょうか.
https://pypi.org/project/nlplot/1.4.0/
