### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [takapy0210/nlplot#7]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.0.5. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary nlplot -w /tmp/ext nlplot==1.0.5
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting nlplot==1.0.5
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/268/60eab173095a1/nlplot-1.0.5.tar.gz (966 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-52cua8_n/nlplot/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-52cua8_n/nlplot/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-52cua8_n/nlplot/pip-egg-info
         cwd: /tmp/pip-wheel-52cua8_n/nlplot/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-52cua8_n/nlplot/setup.py", line 26, in <module>
        install_requires=read_requirements(),
      File "/tmp/pip-wheel-52cua8_n/nlplot/setup.py", line 11, in read_requirements
        with open(reqs_path, 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: './requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by takapy0210** [comment]
Sorry for the late reply.
Thanks letting me know, that was really helpful.

We will also check and merge the PR.
